---
title: "Descriptive Statistics"
author: "Lisa Oshita"
date: "July 11, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Basic descriptive statistics/exploring the variables
### using out_english data set: 
* about 8000 observations
* around 64% of questions were answered (~ 36% unanswered/censored)

### exploring data about the users (the people asking the questions)
* ~80% of users who asked the question were new (member for less than 1 day when the question was posted)
* continuing users (those who have been a member for longer than 1 day), get their questions answered faster than new users do (had lower mean/median time_until_answer)
* KM curves showed that continuing users had a consistently lower survival probability 
* log rank tests: Chisq= 212  on 1 degrees of freedom, p= 0

### looking at the traffic of the questions
### total_views
* min total views: 0, max total views: > 23380
* product categories: Phones, skills, Vehicle, Mac, and Tablet get the highest total views 
* grouping the data by number of tags shows that including tags leads to more views on the question, which also seems like it leads to shorter answer times (lower mean/median avg_time until answer)
* for a lot of the questions with 0 total views, it appears that there were a lot of NAs for the category variable (more so than for the questions with a large number of views), a lot of them also don't include any tags 
* maybe don't consider this variable as much as daily_views (because as time passes it's likely it will get more views)

### daily_views
* max daily_views = 320 (id = 393909, 24 question comments, 7 answer comments, 25 participants (which is also the highest number of participants on any question))
* just from looking at the data set arranged in decreasing order, seems like most of the questions that have a really high amount of daily views fall into the phone cateogry, majority of the questions contain at least 1 tag, pretty much all are answered (answered variable = 1)
* Mac, phone, tablet, vehicle have the highest average daily views
* questions with at least one tag have higher average daily_views than questions with none, and also have a lower avg time_until_answer values
* questions that were characterized correctly (are not NA in the category variable) have higher average daily_views, and lower avg time_until_response values 

### examining distribution of time_until_answer
* min = 30 sec, max = 7,772,000 sec (~90 days) (id = 389776)
* mean = 1281000 sec (~15 days), median = 31650 sec (~8 hours)
* 1st quartile = 3134 sec (52.2 min), 3rd quartile = 1975000 (~23 days) (25% of the questions wre answered before 52 min, and 75% of the questions were answered after 23 days, middle 50% of the data falls between 52 min and 23 days)
* distibution of response is extremely skewed right 
* from distribution it seems like quite a bit of data falls between 30 sec and 1200000 (~14 days)

### examining time_until_answer by categories 
* phone, mac, tablet, pc, and electronics have the most questions (out of 15 total categories)
* Skills category has shortest average time_until_answer, but only has 5 in that category
* Mac has the second shortest average time_until_answer, with a good amount of observations (666)
* PC and then Phone have next shortest average times, with 413 and 2148 observations 
* Camera has the longest average time, with 269 observations
* looking at categories according to median time_until_answer gives similar results (skills, mac and phone have shortest median times)
* distributions of time_until_answer for Mac, PC, Phone are extremely skewed right (exactly like the distribution of time_until_answer for all categories)
* KM curve for survival experiences between product categories shows that: Mac, Phones, and PC have consistently the lowest survival probabilities (get answered quicker)
* camera's have the highest survival probabilities 
* skills category has only complete observed times, all less than 35000, so it's probability curve looks like just a line
* Chisq= 409  on 14 degrees of freedom, p= 0 
* looking at just whether or not a question was NA in the category variable, questions that were categorized correctly (categorized = 1), had a consistently lower survival curve than those that were not (categorized = 0): Chisq= 206  on 1 degrees of freedom, p= 0 
* questions that were categorized correctly have lower average time_until_answer and higher daily_views (consider this in the model?)

### examining time_until_answer according to whether or not it contains a question mark
* 1193/7760 (15%) of the questions contain a question mark
* for almost all categories, questions that contain a question mark seem to get answered faster (lower average and median times) 
* but less than half of the total questions for each category contain question marks- may be contributing to the lower values 
* around 71% of the questions that contain question marks were answered 
* questions about Mac, PC, and skills (but only contains 5 obs), have the highest proportion of questions that contain "?" 
* KM curve for survival experiences between questions containing a question mark and questions that don't show that those with a question mark have consistently lower survival probabilities (they get answered faster)
* chi-square = 72, p-value = 0

### whether or not the text of the question includes "tried" or "searched"
* this may be an indicator of whether or not the user has done research before asking the question
* 15% of questions include "tried" or "searched" in the text 
* looking at the avg time_until_answer grouped by questions with "tried" and questions without show that those with "tried" do tend to have a shorter average, also can see that they have higher average daily views
* survival curves show that questions that include "tried/searched" in the text seem to have lower survival probabilities than those that do not, but log-rank test show no signifcant difference (p-value = 0.07)

### examining title length (look at length of text and device title as well)
* mean = 42 characters
* median = 40 characters
* longest title is 89 characters, shortest is 12 characters
* Doesn't seem to be anything interesting here

### examining device name length
* just from looking at the dataset, questions that have long device names seem like they tend to create NAs in the category variable

### examining text length
* shortest text: 20 characters, longest text: 4814.0
* from histogram of text lengths, a bulk of the questions have text lengths between 20 and 1000 characters long (distribution skewed right)
* seems like categories with longer avg/median text lengths have shorter time_until_answer values

### device length 
* min = 0, max = 136 (id = 390271), mean = 17, median = 16
* distribution of device lengths is skewed right
* didn't really see anything interesting here

### number of tags included in a question
* max number of tags = 4
* 56% of questions don't include any tags
* 43% of the questions that do have a tag only have 1 tag
* seems like there MAY be a slight tendency for questions with more tags to get answers quicker (shorter avg time_until_answer, but also have not as many observations)
* from KM curve it appears that questions that include 2,3,4 have consistently lower survival probabilities than for the questions that don't include tags, or only include 1 (questions that include 1 tag still have consistently lower survival probabilities than those that don't include any)
*Chisq= 48.6  on 4 degrees of freedom, p= 7.06e-10 

### number of images included
* only 4% of the questions contain any images
* min = 0, max = 13 (id = 396580)
* don't see anything here (if looking at the mean time_until_answer grouped by n_images, and mean daily_views)
* survival curves show that there might be a difference in survival experiences
* signficant log-rank test:  Chisq= 44.5  on 11 degrees of freedom, p= 0.00000601 
* after just looking at whether or not a question included any pic, found a signficant difference in survival probabilities (Chisq= 35.6  on 1 degrees of freedom, p= 0.00000000245)
* only 4.4% of questions include any image
* those who have at least one question have lower average time_until_answer values, and higher average daily_views

## Survival analysis statistics 
### KM estimator/curve
* from the KM curve, the survival probability after a question is immediately posted is equal to 1. By ~8000 seconds (~2.2 hours) the survival probability has dropped to about 0.6. By ~ 23,000 seconds (~6.4 hours), survival probability is at about 0.5. By about 230,000 seconds (~2.7 days, 64 hours). After that point, it appears that the survival probability seems to level out at around 0.35-0.4 
* mean survival time = 2,748,083 (45801.38 min, 763.3563hrs, 31.8 days)

### quantiles
* at 857 seconds (14.3 min), 10% of the questions have been answered
* at 3163 seconds (52.7 min), 25% of the questions have been answered
* (median) At 32,966 seconds (9.16 hours), 50% of the questions have been answered 
* 95% confidence interval for median: (28844, 38535) or (8.01 hours, 10.7 hours)
* there is no time for which 75th percentile (since the lowest survival probability = 0.346, and it never reaches 0) (means that we'll never get a total of 75% of questions answered, there will always be some questions that "survive")

### instantaneous hazard rates
* instantaneous hazard drops pretty drastically after question is first posted
* By about 400,000 seconds (~4.6 days), it appears that hazard rate is really close to 0
* looking at the plot, there's a spike in instantaneous hazard around 200,000 seconds (~2.3 days)

### cumulative hazard rates
* increases very quickly until about 400000 seconds (~4-5 days) (indicating that hazard is increasing on that interval), when it starts to even out until it coasts at 1 (indicating that hazard is decreasing)
* do the Nelson Aalen and KM estimators of cumulative hazard look the same becasue the data set is so large?









