---
title: "Model Fitting"
author: "Lisa Oshita"
date: "8/1/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
dir <- file.path(getwd(),"data")
out <- read.csv(file.path(dir, "answers_data.csv"))

library(dplyr)
x <- out %>% 
  tbl_df() %>%
  filter(langid == "en")

x$time_until_answer <- (x$first_answer_date - x$post_date)/3600
empty <- which(is.na(x$time_until_answer))
for (i in empty) {
  x$time_until_answer[i] <- (x$download_date[i] - x$post_date[i])/3600
}

library(stringr)
library(rebus)
library(survival) 
```

```{r, include = FALSE}
#function to get AIC statistics
get_aic <- function(cr_obj, num_parameters, data) {
  aic <- (-2*cr_obj$loglik[2]) + (2*num_parameters)
  return(aic)
}

#function to calculate r-square adjusted
get_rsq_adj <- function(cr_obj, k) {
  r <- unname(summary(cr_obj)$rsq[1])
  n <- summary(cr_obj)$n
  radj <- 1- (((1- (r**2)) * (n - 1))/(n-k-1))
  return(radj)
}
  

#function that takes in character vector and returns a data frame of words and frequencies sorted by most to least frequent, n and stopwrds are an optional arguments
freq_terms <- function(vec, n = NULL, stopwrds = NULL) {
  source <- VectorSource(vec)
  corpus <- VCorpus(source)
  
  if (is.null(stopwrds)) {
    cleaned_corpus <- clean_corpus(corpus) 
    dtm <- DocumentTermMatrix(cleaned_corpus, control = list(weighting = weightTfIdf))
    m <- as.matrix(dtm) 
    freq <- colSums(m)
    freq <- sort(freq, decreasing = TRUE)
    freq_df <- data.frame(word = names(freq), frequency = unname(freq))    
  } else {
    cleaned_corpus <- clean_corpus(corpus, stopwrds) 
    dtm <- DocumentTermMatrix(cleaned_corpus, control = list(weighting = weightTfIdf))
    m <- as.matrix(dtm) 
    freq <- colSums(m)
    freq <- sort(freq, decreasing = TRUE)
    freq_df <- data.frame(word = names(freq), frequency = unname(freq))
  }
  
  if (missing(n)) {
    return(freq_df)
  }
  else {
    return(freq_df[1:n,])
  }
}
```


```{r, include = FALSE}
#changing NA's in category to other
x$category <- as.character(x$category)
x$category[is.na(x$category)] <- "Other"
x$category <- as.factor(x$category)

#pic included
x$pic_included <- 0
x$pic_included[x$n_images != 0] <- 1

#text_length
x$text_length <- str_length(x$text)

#title length
x$title_length <- str_length(x$title)

#device name length
x$device_length <- str_length(x$device)

#posting times
x$post_datetime <- as.POSIXct(x$post_date,origin="1970-01-01")
x$post_d <- format(x$post_datetime, "%m/%d/%y")
x$post_time <- format(x$post_datetime, " %H:%M:%S")
x$post_weekday <- factor(weekdays(x$post_datetime), levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))
x$post_hour <- as.numeric(format(x$post_datetime,"%H"))

x$post_ampm <- "Night"
x$post_ampm[x$post_hour >= 5 & x$post_hour < 12] <- "Morning"
x$post_ampm[x$post_hour >= 12 & x$post_hour < 17] <- "Afternoon" #noon - 5pm 
x$postampm[x$post_hour >= 17 & x$post_hour < 20] <- "Evening" #5pm - 8pm 

#whether or not it was cateogorized correctly
x$categorized <- 0
x$categorized[!is.na(x$category)] <- 1

#length of sentence till first punctuation mark 
x$text_till_punct <- str_locate(x$text, pattern = "[.|?|!]")[,1]
x$text_till_punct[is.na(x$text_till_punct)] <- 5000

#if text contains end punctuation
x$contain_punct <- FALSE
x$contain_punct[!is.na(x$text_till_punct)] <- TRUE

#if the text ends in a punctuation
x$text_end_punct <- str_detect(x$text, pattern = "[.|?|!]$")

#if the title ends in a question mark
x$title_questionmark <- str_detect(x$title, pattern = QUESTION %R% END)

#if the title starts with "Wh"
x$title_begin_wh <- str_detect(str_to_lower(x$title), pattern = "^wh")

#if first letter of title is capitalized
x$capital_title <- str_detect(x$title, pattern = "^[[:upper:]]")

#if first letter of text is capitalized
x$capital_text <- str_detect(x$text, pattern = "^[[:upper:]]")

#if text is in all lower case
x$removed <- str_replace_all(x$text, " ", "")
x$removed <- str_replace_all(x$removed, "[[:punct:]]|[[:digit:]]", "")

x$text_all_lower <- str_detect(x$removed, pattern = "^[[:lower:]]+$")
x <- x[,-which(names(x) == "removed")]

#prior effort
x$prior_effort <- str_detect(str_to_lower(x$text), pattern = or("tried", "searched", "researched", "tested", "replaced", "used", "checked", "investigated", "considered", "measured", "attempted", "inspected", "fitted"))

#gratitude 
x$gratitude <- str_detect(str_to_lower(x$text), pattern = or("please", "thank you", "thanks", "thankful", "appreciate", "appreciated", "grateful"))

#greeting
x$greeting <- str_detect(str_to_lower(x$text), pattern = START %R% or("hey", "hello", "greetings", "hi"))

#update?
x$update <- str_detect(x$text, pattern = "===")

#tags
#indicator variable for tags/no tags included
x$tag_included <- 0
x$tag_included[x$n_tags != 0] <- 1

#matrix of tags (splitting up tags variable wherever there's a comma)
split_tags <- str_split(x$tags, ", ", simplify = TRUE)

#character vector of all tags (empty strings removed)
tag_vector <- as.vector(split_tags)
tag_vector <- tag_vector[which(tag_vector != "")]

unique_tags <- unique(tag_vector)

#average tag length
x$avg_tag_length <- NA
not_na <- which(x$tags != "")
for (i in not_na) {
  total_char <- sum(str_length(as.vector(split_tags[i,])))
  total_tags <- sum(as.vector(split_tags[i,]) != "")
  x$avg_tag_length[i] <- total_char / total_tags
}
x$avg_tag_length[is.na(x$avg_tag_length)] <- 0

x$max_tagwords <- rep(0, nrow(x))
for (i in which(x$n_tags != 0)) {
  tags <- as.vector(split_tags[i,])
  x$max_tagwords[i] <- max(str_count(tags, pattern = "\\w+"))
}

#frequency of tags
tag_freq <- data.frame(tag = unique_tags, percent = purrr::map_dbl(unique_tags, ~mean(rowSums(split_tags == .) > 0)))

tag_freq <- tag_freq %>%
              arrange(desc(percent))
top50 <- tag_freq[1:50,]

x$tag1 <- split_tags[,1]
x$tag2 <- split_tags[,2]
x$tag3 <- split_tags[,3]
x$tag4 <- split_tags[,4]

assign_score <- function(data, variable) {
  score <- rep(0, nrow(data))
  notempty <- which(data[[variable]] != "")
  for (i in notempty) {
    score[i] <- tag_freq$percent[which(tag_freq$tag == data[[variable]][i])]
  }
  return(score)
}

x$score1 <- assign_score(x, "tag1")
x$score2 <- assign_score(x, "tag2")
x$score3 <- assign_score(x, "tag3")
x$score4 <- assign_score(x, "tag4")

x$avg_tag_score <- (x$score1 + x$score2 + x$score3 + x$score4)/x$n_tags
x$avg_tag_score[is.nan(x$avg_tag_score)] <- 0

percentile80 <- quantile(x$avg_tag_score, probs = 0.80)

x$frequent_tag <- FALSE
x$frequent_tag[x$avg_tag_score >= percentile80] <- TRUE

top50tag <- as.character(top50$tag)

#function to check if tag in top50
contain_tag <- function(tag, data) {
  contain <- rep(NA, nrow(data))
  for(i in which(data[[tag]] != "")) {
    if (data[[tag]][i] %in% top50tag) {
      contain[i] <- TRUE
      } else {
        contain[i] <- FALSE
      }
    }
  return(contain)
}

containdf <- data.frame(c1 = contain_tag("tag1", data = x),
                        c2 = contain_tag("tag2", data = x),
                        c3 = contain_tag("tag3", data = x),
                        c4 = contain_tag("tag4", data = x))

x$contain_toptag <- rep(FALSE, nrow(x))
for (j in which(!is.na(containdf$c1))) {
  if (TRUE %in% containdf[j,]) {
    x$contain_toptag[j] <- TRUE
  } else {
    x$contain_toptag[j] <- FALSE
  }
}

#frequent terms in unanswered/answered questions
answered <- x %>%
  tbl_df() %>% 
  filter(answered == 1)

unanswered <- x %>%
  tbl_df() %>% 
  filter(answered == 0)

library(qdap)
library(tm)
terms_a <- freq_terms(answered$title)
terms_a$prop_in_answered <- terms_a$frequency/nrow(terms_a)
colnames(terms_a)[2] <- "frequency_a"

terms_u <- freq_terms(unanswered$title)
terms_u$prop_in_unanswered <- terms_u$frequency/nrow(terms_u)
colnames(terms_u)[2] <- "frequency_u"

combined <- full_join(terms_a, terms_u, by = "word")
combined$ratio <- combined$prop_in_answered / combined$prop_in_unanswered

p_threshold <- 0.01
ratio_threshold <- 1

freq_terms_u <- combined %>%
                  filter(prop_in_unanswered > p_threshold) %>%
                  filter(ratio < ratio_threshold)
freq_terms_a <- combined %>%
                  filter(prop_in_answered > p_threshold) %>%
                  filter(ratio > ratio_threshold)

x$contain_unanswered <- str_detect(as.character(x$title), pattern = or1(freq_terms_u$word))
x$contain_answered <- str_detect(as.character(x$title), pattern = or1(freq_terms_a$word))

#ratio of newlines to length of text
x$newline_ratio <- str_count(x$text, pattern = "\n")/str_length(x$text)

```


```{r, echo = FALSE}
cr1 <- coxph(Surv(time_until_answer, answered) ~ category + as.factor(new_user) + 
                  as.factor(n_tags) + as.factor(pic_included) + text_length + title_length + 
                  device_length + post_weekday + as.factor(post_hour) + text_till_punct + 
                  text_end_punct + title_questionmark + title_begin_wh + 
                  capital_title + capital_text + text_all_lower + prior_effort + gratitude + 
                  greeting + update + avg_tag_length + max_tagwords + avg_tag_score + 
                  frequent_tag + contain_toptag + contain_unanswered + contain_answered + 
                  newline_ratio, data = x)
s <- summary(cr1)
s$rsq
get_aic(cr1, 72, data = x) #83471.68
get_rsq_adj(cr1, 72) #0.00513921

#removed greeting and text_end punct (p-values > .8)
cr2 <- coxph(Surv(time_until_answer, answered) ~ category + as.factor(new_user) + 
                  as.factor(n_tags) + as.factor(pic_included) + text_length + title_length + 
                  device_length + post_weekday + as.factor(post_hour) + text_till_punct + 
                  title_questionmark + title_begin_wh + 
                  capital_title + capital_text + text_all_lower + prior_effort + gratitude + 
                  update + avg_tag_length + max_tagwords + avg_tag_score + 
                  frequent_tag + contain_toptag + contain_unanswered + contain_answered + 
                  newline_ratio, data = x)
summary(cr2)
get_aic(cr2, 70, data = x) #83467.71
get_rsq_adj(cr2, 70) #0.005397121

#removed max_tagwords
cr3 <- coxph(Surv(time_until_answer, answered) ~ category + as.factor(new_user) + 
                  as.factor(n_tags) + as.factor(pic_included) + text_length + title_length + 
                  device_length + post_weekday + as.factor(post_hour) + text_till_punct + 
                  title_questionmark + title_begin_wh + 
                  capital_title + capital_text + text_all_lower + prior_effort + gratitude + 
                  update + avg_tag_length + avg_tag_score + 
                  frequent_tag + contain_toptag + contain_unanswered + contain_answered + 
                  newline_ratio, data = x)
summary(cr3)
get_aic(cr3, 69, data = x) #83465.91
get_rsq_adj(cr3, 69) #0.005520927

#removed avg_tag_length
cr4 <- coxph(Surv(time_until_answer, answered) ~ category + as.factor(new_user) + 
                  as.factor(n_tags) + as.factor(pic_included) + text_length + title_length + 
                  device_length + post_weekday + as.factor(post_hour) + text_till_punct + 
                  title_questionmark + title_begin_wh + 
                  capital_title + capital_text + text_all_lower + prior_effort + gratitude + 
                  update + avg_tag_score + 
                  frequent_tag + contain_toptag + contain_unanswered + contain_answered + 
                  newline_ratio, data = x)
summary(cr4)
get_aic(cr4, 68, data = x) #83463.95
get_rsq_adj(cr4, 68) #0.005649183

#removed text_till_punct
cr5 <- coxph(Surv(time_until_answer, answered) ~ category + as.factor(new_user) + 
                  as.factor(n_tags) + as.factor(pic_included) + text_length + title_length + 
                  device_length + post_weekday + as.factor(post_hour) + 
                  title_questionmark + title_begin_wh + 
                  capital_title + capital_text + text_all_lower + prior_effort + gratitude + 
                  update + avg_tag_score + 
                  frequent_tag + contain_toptag + contain_unanswered + contain_answered + 
                  newline_ratio, data = x)
summary(cr5)
get_aic(cr5, 67, data = x) #83462.4
get_rsq_adj(cr5, 67) #0.005766099

#removing n_tags
cr6 <- coxph(Surv(time_until_answer, answered) ~ category + as.factor(new_user) + 
                  as.factor(pic_included) + text_length + title_length + 
                  device_length + post_weekday + as.factor(post_hour) + 
                  title_questionmark + title_begin_wh + 
                  capital_title + capital_text + text_all_lower + prior_effort + gratitude + 
                  update + avg_tag_score + 
                  frequent_tag + contain_toptag + contain_unanswered + contain_answered + 
                  newline_ratio, data = x)
summary(cr6)
get_aic(cr6, 63, data = x) # 83455.8
get_rsq_adj(cr6, 63) #0.00624444

#remove text_length
cr7 <- coxph(Surv(time_until_answer, answered) ~ category + as.factor(new_user) + 
                  as.factor(pic_included) + title_length + 
                  device_length + post_weekday + as.factor(post_hour) + 
                  title_questionmark + title_begin_wh + 
                  capital_title + capital_text + text_all_lower + prior_effort + gratitude + 
                  update + avg_tag_score + 
                  frequent_tag + contain_toptag + contain_unanswered + contain_answered + 
                  newline_ratio, data = x)
summary(cr7)
get_aic(cr7, 62, data = x) #83455.28
get_rsq_adj(cr7, 62) #0.006333204

#remove title_length
cr8 <- coxph(Surv(time_until_answer, answered) ~ category + as.factor(new_user) + 
                  as.factor(pic_included) + 
                  device_length + post_weekday + as.factor(post_hour) + 
                  title_questionmark + title_begin_wh + 
                  capital_title + capital_text + text_all_lower + prior_effort + gratitude + 
                  update + avg_tag_score + 
                  frequent_tag + contain_toptag + contain_unanswered + contain_answered + 
                  newline_ratio, data = x)
summary(cr8)
get_aic(cr8, 61, data = x) #83454.54
get_rsq_adj(cr8, 61) #0.006427927

#remove pic_included
cr9 <- coxph(Surv(time_until_answer, answered) ~ category + as.factor(new_user) + 
                  device_length + post_weekday + as.factor(post_hour) + 
                  title_questionmark + title_begin_wh + 
                  capital_title + capital_text + text_all_lower + prior_effort + gratitude + 
                  update + avg_tag_score + 
                  frequent_tag + contain_toptag + contain_unanswered + contain_answered + 
                  newline_ratio, data = x)
summary(cr9)
get_aic(cr9, 60, data = x) #83454.3
get_rsq_adj(cr9, 60) #0.0065088

#remove prior_effort
cr10 <- coxph(Surv(time_until_answer, answered) ~ category + as.factor(new_user) + 
                  device_length + post_weekday + as.factor(post_hour) + 
                  title_questionmark + title_begin_wh + 
                  capital_title + capital_text + text_all_lower + gratitude + 
                  update + avg_tag_score + 
                  frequent_tag + contain_toptag + contain_unanswered + contain_answered + 
                  newline_ratio, data = x)
summary(cr10)
get_aic(cr10, 59, data = x) #83454.39 aic went up 
get_rsq_adj(cr10, 59) #0.00658092




```
