---
title: "Practice with parametric distributions"
author: "Lisa Oshita"
date: "July 10, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### import the data
```{r}
dir <- file.path(getwd(),"data")
out <- read.csv(file.path(dir, "answers_data.csv"))

#creating time to event variable
out$time_until_answer <- out$first_answer_date - out$post_date
#filling in the NAs
empty <- which(is.na(out$time_until_answer))
for (i in empty) {
  out$time_until_answer[i] <- out$download_date[i] - out$post_date[i]
}

#subsetting to include only observations in english with positive time to event values
library(dplyr)
out1 <- out %>% 
          tbl_df() %>% 
          filter(langid == "en") %>%
          filter(time_until_answer > 0)
```

### finding parameter estimates with flexsurv package
```{r}
surv_object <- Surv(out1$time_until_answer, out1$answered, type = "right")

library(flexsurv)

weibull <- flexsurvreg(surv_object~1, data = out1, dist = "weibull")
weibull
plot(weibull)

exp <- flexsurvreg(surv_object~1, data = out1, dist = "exp")
exp
plot(exp)

lnormal <- flexsurvreg(surv_object~1, data = out1, dist = "lnorm")
lnormal
plot(lnormal)
#has lowest AIC of the 4 distributions

logistic <- flexsurvreg(surv_object~1, data = out1, dist = "llogis")
logistic
plot(logistic)

```

### setting up probability plots to assess fit
```{r}
#are the plots actually following the line?- maybe scale too large to see it correctly 
qqplot(rweibull(15000, shape = 2.26e-01, scale = 1.32e+06), out1$time_until_answer, xlab = "rweibull values", ylab = "seconds")
abline(0,1)

#narrowed scope of x-axis to get a closer look at the plot-data does not fit a weibull distribution (not sure if did this correctly)
qqplot(rweibull(15000, shape = 2.26e-01, scale = 1.32e+06), out1$time_until_answer, xlim = c(0,1e+8), xlab = "rweibull values", ylab = "seconds")
abline(0,1)
#data doesn't fit weibull distribution

qqplot(rexp(15000, rate = 4.86e-07), out1$time_until_answer, xlab = "rexp values", ylab = "seconds")
abline(0,1)
#data doesn't fit an exponential distribution either

qqplot(rlnorm(15000, meanlog = 12.1129, sdlog = 4.8951), out1$time_until_answer, xlab = "rlnorm values", ylab = "seconds", xlim = c(0, 5e+7))
abline(0,1)
#data doesn't fit lognormal distribution 

qqplot(rlogis(15000, location = 3.30e-01, scale = 1.28e+05), out1$time_until_answer)
abline(0,1)
#data does not fit logistic distribution 
```


### learning about flexsurvreg (using different data)
```{r}
time <- c(5,8,12,24,32,17,16,17,19,30)
censor <- c(1,1,1,1,1,1,0,0,0,0)
example <- data.frame(time, censor)

s <- Surv(example$time, example$censor, type = "right")
exponential <- flexsurvreg(s~1, data = example, dist = "exp")
exponential
survreg(s~1, data = example, dist = "exp")

data(ovarian)
fitg <- flexsurvreg(formula = Surv(futime, fustat) ~ 1, data = ovarian, dist="gengamma")
fitg
fitw <- flexsurvreg(formula = Surv(futime, fustat) ~ 1, data = ovarian, dist="weibull")
fitw
plot(fitg)
lines(fitw, col="blue", lwd.ci=1, lty.ci=1)
```

### trying to apply fitdistrplus functions to data (NOT WORKING)
```{r}
library(fitdistrplus)

#creating the data frame to use in the function
left <- right <- out1$time_until_answer
right[out1$answered == 0] <- NA_integer_
censdata <- data.frame(left, right)

#fitweibull <- fitdistcens(censdata, distr = "weibull")

```

### practicing with fitdistcens function on different dataset 
```{r}
data("salinity")
str(salinity)
data("smokedfish")

fsal.ln <- fitdistcens(salinity, "lnorm")
fsal.ln

log10EC50 <-log10(fluazinam)
fln <- fitdistcens(log10EC50,"norm")
fln
summary(fln)
plot(fln)
```



